# Usa uma imagem Node.js como base
#FROM node:18-alpine
#
## Define o diretório de trabalho
#WORKDIR /app
#
## Copia o package.json e instala as dependências
#COPY package*.json ./
#
#RUN npm install
#
## Copia o restante dos arquivos do projeto
#COPY . .
#
## Torne o entrypoint executável
##RUN chmod +x scripts/entrypoint.sh
#
## Expõe a porta usada pelo NestJS
#EXPOSE 3000
#
## Configure o entrypoint
## ENTRYPOINT ["sh", "scripts/entrypoint.sh"]
#
## Comando para iniciar o servidor
#CMD ["npm", "run", "start:dev"]
